apiVersion: v1
kind: Pod
metadata:
  name: nginx-02
  labels:
    env: test
spec:
  containers:
  - name: nginx-02
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "key2"
    operator: "Equal"
    value: "value2"
    effect: "NoExecute"  
