apiVersion: v1
kind: LimitRange
metadata:
  name: memory-resource-constraint
spec:
  limits:
  - default:
      memory: "500m" #limit de memory
    defaultRequest:
      memory: "500m" #request
    max:
      memory: "1" #limit de memory
    min:
      memory: 100m
    type: Container