apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels: 
    app: myapp-svc
    type: backend
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    app: myapp
    type: frontend