apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-secret
  labels:
    name: simple-pod-secret
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 8080
      envFrom:
        - secretRef:
            name: app-secret