apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    name: simple-pod-variables
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
       - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-config